--- 
abstract: A Logging Role for Moose
author: 
  - Brandon Black C<< <blblack@gmail.com> >>
build_requires: 
  Test::More: 0.42
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: MooseX-LazyLogDispatch
no_index: 
  directory: 
    - inc
    - t
provides: 
  MooseX::LazyLogDispatch: 
    file: lib/MooseX/LazyLogDispatch.pm
    version: 0.01
  MooseX::LazyLogDispatch::Levels: 
    file: lib/MooseX/LazyLogDispatch/Levels.pm
    version: 0.01
requires: 
  Log::Dispatch::Configurator: 0
  Moose: 0
version: 0.01
